### ISSUE TITLE
Thanks for 0nyx!

### ISSUE THREAD

**Issue by fanf** [sixsixfive/0nyX-Suite#13]
That's not really an issue, I just wanted to thank you for 0nyx suite! 
I think it's the first time I successfully have a GTK-2 dark-theme in eclipse thanks to 0nyx 

The code is very oganized, and even if I don't understand anything about GTK themes, I was able to change scrollbar size in no time (and I was able to also remove most of the lost space in eclipse (it's a design horror - but that's not the subject :) 

So just thank you !

**Comment by sixsixfive** [comment]
thx, Im glad its working for you
