### ISSUE TITLE
Icon Requests

### ISSUE THREAD

**Issue by chuutatsu** [sixsixfive/0nyX-Suite#7]
1. I installed _telegram-desktop_ package from AUR. In the Whisker menu it used icon from Phlat BUT it has no Telegram icon tray. The original blue paper plane is used instead. Will you add the tray icon in the future?

2. Also, please add Phlat icons for Rambox, Spotify, Fcitx, ClamTK and Corebird.

Thanks in advance!

**Comment by sixsixfive** [comment]
@1 sorry but I guess thats impossible web/electron/javascript apps often don't use the systems icons

@2 np will add them however rambox and spotify are two other webapps so don't expect that their systray or UI icons will change

**Comment by chuutatsu** [comment]
Alright. About the tray icons problem, it's fine.

Thanks again for additional icons in the future.

**Comment by bil-elmoussaoui** [comment]
@sixsixfive Hey, about the tray icons problem. I have been working on a solution that works quite well with a lot of apps at the moment. Almost 100 :) Especially electron apps, and they can use the system icons without breaking anything

**Comment by chuutatsu** [comment]
@bil-elmoussaoui Are you referring to Hardcode-Tray?

@sixsixfive I have noticed that Fcitx and Spotify already get new icons. Great.

**Comment by bil-elmoussaoui** [comment]
@chuutatsu Yeah :)

**Comment by sixsixfive** [comment]
@chuutatsu 

there is now a hp icon, however the hplip icon is loaded from a hardcoded path sou you have to replace it there by hand.
